spring.application.name=U-Minimalist
server.port=9090
spring.thymeleaf.cache=false

# ===== DOCKER COMPOSE CONFIGURATION =====
spring.docker.compose.lifecycle-management=start-only
spring.docker.compose.file=docker-compose.yml


spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:14333;databaseName=UMinimalistDB;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:12345}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ===== PAYPAL CONFIGURATION =====
paypal.client.id=${PAYPAL_CLIENT_ID:ASQObPn3MhN2JYgApUjNynUkPHsXPaITQ-WOOaQbBKm0JP4nikCyGA6Z5dvpuDA05BZyZtssC3p-VVu1}
paypal.client.secret=${PAYPAL_CLIENT_SECRET:EOxE3cp-YOQ7gXz40rtIt4LRlf-loQjVXt4DccjucQ9f0eVsvP8HolH5PF9Z_FwwTJbjATAX-BJXG_ld}
paypal.mode=${PAYPAL_MODE:sandbox}
paypal.return-url=${PAYPAL_RETURN_URL:http://localhost:9090/paypal/success}
paypal.cancel-url=${PAYPAL_CANCEL_URL:http://localhost:9090/paypal/cancel}

# ===== CLOUDINARY CONFIGURATION =====
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dcroyqkoa}
cloudinary.api-key=${CLOUDINARY_API_KEY:636328917892277}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:Cdy5FvBl0Mi49C70C_12sNdz_bs}
# ===== MULTIPART FILE UPLOAD CONFIGURATION =====
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-swallow-size=50MB
