spring.application.name=U-Minimalist
server.port=9090
spring.thymeleaf.cache=false

spring.datasource.url=${DB_URL:jdbc:sqlserver://localhost:14333;databaseName=UMinimalistDB;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${DB_USERNAME:sa}
spring.datasource.password=${DB_PASSWORD:Sa123456@}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ===== VNPAY CONFIGURATION =====
vnpay.tmn-code=2AS5E3Q3
vnpay.hash-secret=5DJ4Q95ESAEMBAM3H68QBKQ616DHTSZ4
vnpay.payment-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:9090/checkout/payment-return

# ===== CLOUDINARY CONFIGURATION =====
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:}
cloudinary.api-key=${CLOUDINARY_API_KEY:}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:}
# ===== MULTIPART FILE UPLOAD CONFIGURATION =====
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-swallow-size=50MB
